### ISSUE TITLE
Handling several modules

### ISSUE THREAD

**Issue by genfersee** [harkle/fallblatt-module#3]
Hello,

This module works really great, thanky ou so much.
I a question: how can I control several modules? Can this be done via the same web GUI?
I see there is an architecture.md file in the project but do not see how to use it.

Thanks in advance and kind regards,
Genfersee

**Comment by genfersee** [comment]
If I understand correctly, in RS-485, I can connect several modules in parallel.
Then, I tried to modify the config.json to add a second module, but the program is crashing.
What would be the correct syntax to add 2 modules in the config.json?

**Comment by harkle** [comment]
Each module has is own address. So if they are connected together on the same RS-485 bus you can controls them all with the same computer/software. BUT! The software I design is not made to controll multiple modules with one software. Its designed for each module to have his one RaspberryPi in order to control it individually. But you can easily transform my software to act like this. I'have dont this to create a clock.

**Comment by genfersee** [comment]
Thanks for your answer! I would be very interested to see your clock code since I am not very familiar with js! I should be able to modify the code If I would know how to initialize a second module in the code.

**Comment by genfersee** [comment]
I finally managed to have it work on several modules :) Thanks!
